### ISSUE TITLE
Inpainting is not working.

### ISSUE THREAD

**Issue by DarkAlchy** [isekaidev/stable.art#18]
Lasso the selection
![image](https://user-images.githubusercontent.com/10561690/213799110-2cfb9431-50fa-4f44-88f6-4e247916f558.png)

Click inpainting then hit generate to get these errors:
![image](https://user-images.githubusercontent.com/10561690/213799013-d3d1437d-a27b-43fb-921c-e66d8d9550e7.png)
![image](https://user-images.githubusercontent.com/10561690/213799199-cb34a16a-bcaf-4f46-8843-094e1800d62b.png)

PS 23.3.2

**Comment by jauri1** [comment]
I can not confirm. Everything works well with version 24.*.*

**Comment by DarkAlchy** [comment]
> I can not confirm. Everything works well with `version 24.*.*`

Great, except this said 23.3.0 and I am not upgrading.
