### ISSUE TITLE
Dropdown for model selection is greyed out and displays "default" no matter what model is loaded

### ISSUE THREAD

**Issue by JTJutajoh** [isekaidev/stable.art#19]
This was working a few days ago when I used the plugin last, but now the dropdown for model switching is greyed out.
![image](https://user-images.githubusercontent.com/1093375/213840269-e89946e2-d9f1-4404-abd3-3c6aea5c16e1.png)

**Comment by isekaidev** [comment]
Could you try to remove an url in the endpoint field, insert it again, and click outside of the field? Will be the dropdown still grey?

**Comment by JTJutajoh** [comment]
> Could you try to remove an url in the endpoint field, insert it again, and click outside of the field? Will be the dropdown still grey?

Yep, you're right that made it work again.

**Comment by DarkAlchy** [comment]
Worked for me as well.
