### ISSUE TITLE
Inpainting scaled wrong

### ISSUE THREAD

**Issue by filliptm** [isekaidev/stable.art#2]
so far so good! im loving the simplicity of the plugin. 

When inpainting the results display at the wrong scale. If i select a 200x200 pixel mask, when displaying the renders, it scales them up almost 400% from the top left point of the mask
![Screen Shot 2023-01-17 at 2 49 20 PM](https://user-images.githubusercontent.com/55672949/212997634-c5d34f30-ca4d-4f56-856a-df1e49217071.png)

**Comment by isekaidev** [comment]
Could you please provide more examples of what you selected, what you wanted, and what you got (PSD also would be perfect)? Cannot reproduce this myself, so do not fully understand what "scales them up almost 400%" means. The generated square seems even less than 200x200?

**Comment by filliptm** [comment]
Here is a video showing the process, the pixel mask size doesn't seem to effect anything, sorry for the misunderstanding 

https://imgur.com/a/dOst6uG

**Comment by filliptm** [comment]
Photoshop version 23.5.3
back end: Gradio share link

**Comment by isekaidev** [comment]
Thanks for the video. What is the size of the original and generated images? Does this happen for every image and selection or only sometimes?

**Comment by filliptm** [comment]
No problem 🤙 

The original image/canvas size is 1200x1600

The images being rendered were around the 700-800x800 mark. Changing the size of the render doesn't seem to help either. Seems to happen every time regardless of selection method

**Comment by Volantk** [comment]
Same issue, in all modes. 

A couple of numbers that could help:
200x200px selection becomes 256x256px.
100x200px becomes 170x256px.

Top left corner stays in place.

**Comment by JTJutajoh** [comment]
I was having this issue as well and I believe I have tracked down the cause. It seems to happen only with documents with nonstandard DPI settings. Photoshop defaults to 72 DPI, and at that scale it works correctly. If you alter the DPI of the image (unchecking the Resample checkbox so it stays the same pixel resolution), this bug manifests. You can also get the inpainted section to be scaled _down_ by setting the DPI to something below 72.

For now a functional workaround seems to be to set the DPI of your document to 72.

**Comment by isekaidev** [comment]
Fixed. Could you test?

**Comment by filliptm** [comment]
Nice, everything is working well ^.^
