### ISSUE TITLE
Allow for inpaint masking or at the very least, feathering.

### ISSUE THREAD

**Issue by MatheusLynar** [isekaidev/stable.art#22]
Inpainting is probably the most powerful use of Photoshop + Stable Diffusion. However, without mask + mask blur, many of the generated images won't blend nicely to the rest of the image.

It would be great if you could add this feature (or at least a mask blur automatically on the border of the selection) to your plugin. 
Thank you for your creation!

**Comment by Woisek** [comment]
Just use quick mask to paint and then feather it ... if I understand your issue correctly ...

**Comment by MatheusLynar** [comment]
> Just use quick mask to paint and then feather it ... if I understand your issue correctly ...

Even if you feather your selection or your mask, the plugin will still generate an image with "hard borders". It's a very different result than inpainting with the "mask blur" setting on the webui, which will take the image surroundings into account, creating a much more natural blending without requiring further editing.

**Comment by JTJutajoh** [comment]
I think the best way to solve this problem would be to do like I suggested in #5 which would be that the generation automatically gets a layer mask that matches the initial selection, including feathering.

**Comment by Woisek** [comment]
Another would be to make the selection a bit bigger and then erase/mask the edges where needed. Would have the advantage to have more control over the process.
I did this on my last image.

**Comment by isekaidev** [comment]
Done.
Guys, could you test and give feedback on how it works for you?

**Comment by Woisek** [comment]
Looking good. Mask is generated with a default blur to adjust. Great!

**Comment by JTJutajoh** [comment]
> Done. Guys, could you test and give feedback on how it works for you?

Almost perfect! However while testing it I noticed what I think is a new problem. In short, if I strongly feather a lasso selection, the bounds of the inpainting region seem to be too small. As if it's clipping the alpha from the selection too high and missing the just barely opaque pixels. The end result is that the rectangle that gets inpainted is smaller than the mask/selection, so you get hard edges at the end of the rectangle. I'll get some examples and make a separate issue for it.
