### ISSUE TITLE
Failed to load stable.art when not connected to the internet

### ISSUE THREAD

**Issue by GBaige** [isekaidev/stable.art#23]
I want to use my own, local instance of stable-diffusion with AUTOMATIC1111's webui as the backend, I've already set the --api parameter, but the plugin fails to load if I'm not connected to the internet. Why?

I'm assuming this is a bug since it wouldn't make sense to _need_ to be online if I'm going to connect to a local instance (127.0.0.1:7860 being the default for AUTOMATIC1111's webui). Otherwise the plugin works as expected.

**Comment by isekaidev** [comment]
Duplicate #12 
I plan to add an offline mod after fixing the major bugs and adding outpainting.
