### ISSUE TITLE
Failed to load Stable.art

### ISSUE THREAD

**Issue by ExoSilica** [isekaidev/stable.art#27]
Hi there,

I am having an issue that I cannot seem to resolved. These are some of the things that I've done and I still get the same error.

- Reinstalled the latest version of Adobe Photoshop.
- Disable all firewall app.
- Tried to load Photoshop from new windows admin user.
- Load Photoshop as Admin.
- Load Automatic1111 before starting Photoshop.
- Adding, removing, reinstalling Stable.art, redownload CCX and tried again.
-

I've installed this at my work computer and it has no problem, but something on my home computer is causing a problem. Appreciate your assistance.

![image](https://user-images.githubusercontent.com/115336928/215022280-3aeffe75-063b-4dd9-ae44-c810450a0617.png)

**Comment by ExoSilica** [comment]
Okay, I solved my own problem just now. What I did was go into window's defender firewall setting and i restored everything to default. This got it to working now. I am not 110% sure that was the remedy but I didn't do anything else that would have gotten this going.

![image](https://user-images.githubusercontent.com/115336928/215024234-198ffba3-6ffa-4240-9cfe-0709561a1d1b.png)

**Comment by isekaidev** [comment]
Duplicate #12 
Basically, it means, that your PC cannot load https://stable.art/plugin-code/js/app.js, so yes, most likely, the firewall was the source of the problem. Offline mod is in the plans.
