### ISSUE TITLE
Plugin not displayed in plugins panel

### ISSUE THREAD

**Issue by tommcg** [isekaidev/stable.art#29]
I'm using PS version 23.4.2 and after adding the plugin into the plugins folder, it does not show in the plugins menu. Does the plugin go somewhere else? I have tried unzipping the ccx file and doing a manual install as well.

**Comment by Gbronski** [comment]
Unzipped the .ccx and placing it in plugins manually does work for me

**Comment by isekaidev** [comment]
I did not test a manual installation, but redditors said this instruction worked for them. 
https://www.youtube.com/watch?v=bnpeWwVdlMY
