### ISSUE TITLE
Failed to connect to my server

### ISSUE THREAD

**Issue by WuZifan** [isekaidev/stable.art#31]
<img width="1712" alt="image" src="https://user-images.githubusercontent.com/22706545/215464244-fc2f7380-5fdb-4dcb-9d0e-0a5328e5a320.png">

my server is listening the port 80 and can be accessed from my laptop;

but on the same laptop, in PS and stable.art, it just can't connect to it.

any suggestions?

**Comment by isekaidev** [comment]
Try to change `https://` to `http://`

**Comment by WuZifan** [comment]
> 

still not working

my lunch command: '--listen --api --port 80'

**Comment by WuZifan** [comment]
> Try to change `https://` to `http://`

It works! thank you!
