### ISSUE TITLE
Inpaint rectangle with strongly feathered selection is too small

### ISSUE THREAD

**Issue by JTJutajoh** [isekaidev/stable.art#36]
When using a lasso selection that has been strongly feathered to do inpainting, the rectangle that is used for inpainting is too small and does not include the entire selected area.

**Steps to Reproduce:**

1. Make a lasso selection
2. Feather the selection by a significant amount (15px was used in my examples, on a 1920x1080 image)
3. Use the plugin to perform an inpaint using this selection, using a relatively high denoising strength to make the problem more obvious.
4. Observe that the inpainted region does not include the entire selection

**Expected Results**
The rectangle used for inpainting should include _any pixels_ that are selected at all, even if the selection mask is mostly transparent for that pixel.

**Actual Results**
The selection mask seems to be getting alpha clipped, resulting in mostly transparent (deselected) pixels being ignored and the rectangle being too small. The visible result is that there are hard edges in the inpainted area.

**Examples**
A feathered lasso selection on the original image
![Photoshop_tWW5RY88Ur](https://user-images.githubusercontent.com/1093375/216003829-0a1078c8-a8b4-47be-ab3d-7c930155a0cd.png)

A visual representation of that selection by filling it with solid white. Note the strong feathering and mostly transparent pixels that go even outside of the lasso "marching ants" graphic.
![Photoshop_3BALD3HSmS](https://user-images.githubusercontent.com/1093375/216003342-fc052774-a419-49d7-b1ab-1cd01d5bb5cc.png)

A couple of inpainting results using the above selection. Higher denoising strengths make it more obvious. Notice the hard edges of the rectangle that fall well within the selection.

![Photoshop_BnY8dKnY5X](https://user-images.githubusercontent.com/1093375/216003508-e8ddd45f-7330-4d8e-beda-ab863aa1a5c2.png)
![Photoshop_VSj1XvEKMQ](https://user-images.githubusercontent.com/1093375/216003517-c25c6eec-c3f2-44c1-8444-e77bcb2d2924.png)

**Comment by isekaidev** [comment]
Fixed, could you check it?

**Comment by JTJutajoh** [comment]
Yep, looks perfect to me now.
