### ISSUE TITLE
Resolution override

### ISSUE THREAD

**Issue by JTJutajoh** [isekaidev/stable.art#4]
An option in the UI to directly set what pixel resolution the generation should be generated at. If this plugin is used on relatively large documents (2000px is not uncommon for digital painting) with a standard GPU such as a 3080, it runs out of memory. The only solution is to inpaint smaller sections or manually scale the image down before performing inference.

I think the ideal solution would be to have an optional setting (Maybe under a collapsed "Advanced" section?) for manually setting what resolution it will be generated at.

**Comment by Danamir** [comment]
I added a supersampling setting to inpaint in PR #46, you may want to check it out. With a minor change it could be used as a downsampling method.

**Comment by isekaidev** [comment]
Done 66f1d719b3abf66444615273c57f67a9a313918f

<img width="450" alt="image" src="https://user-images.githubusercontent.com/118139897/223084955-152a0e99-5665-4bc7-ab94-6fa0604736b1.png">
