### ISSUE TITLE
Question: Why it can't be used on lower versions of Photoshop

### ISSUE THREAD

**Issue by Who-is-dk** [isekaidev/stable.art#48]
Is it because of uxp or some special support in new version

**Comment by isekaidev** [comment]
> Is it because of uxp

Yep, this is a citation from Adobe Docs:

> Enter 23.0.0 as the minimum version in the Host Application Version field. Earlier versions of Photoshop do not support plugins written with UXP. 

Also, I do not remember a specific name, but the plugin uses one method that was added in 23.3.
