### ISSUE TITLE
Inpainting inserts Smart Objects with layer mask matching the initial selection

### ISSUE THREAD

**Issue by JTJutajoh** [isekaidev/stable.art#5]
When using a non-rectangular selection to perform inpainting, such as a lasso selection, the resulting Smart Object should come with a layer mask that masks out the parts that were not included in the selection. This would be especially useful when using more advanced selections such as a feathered lasso selection.

**Comment by JTJutajoh** [comment]
An alternative to this would be an option to keep the selection active after the smart object has been inserted, so that it can be used immediately to create this mask. Honestly, both of these options would be nice to have.

**Comment by Alchete** [comment]
Every time I render the selection goes away, such that it needs to be made again.  Is this the intended use-model or am I doing it wrong?  The selection needs to persist after rendering, otherwise this is a very troublesome workflow.

**Comment by isekaidev** [comment]
@Alchete This is a Photoshop limitation - it itself removes the selection, but I am working on a workaround.
However, if you want just to generate more images with the same selection, then you can click "Generate more", and it will use the same selection but new parameters (e.g. prompt, steps, sampling method, etc).

**Comment by isekaidev** [comment]
Done. Could you test and give feedback on how it works for you?

**Comment by JTJutajoh** [comment]
> Done. Could you test and give feedback on how it works for you?

Almost perfect, the process of creating an inpainting with a layer mask is exactly what I was hoping for. There is only one problem, I made this separate issue about it: #36
