### ISSUE TITLE
A way to accept more than just one result from a batch

### ISSUE THREAD

**Issue by JTJutajoh** [isekaidev/stable.art#9]
Sometimes two different images in a batch can both have different elements that they do better than each other, and the ideal result is to accept them both and blend them together to get the best combination. Currently doing this requires manually copying and pasting a generation and then accepting another one. It would be very nice to have some option to choose more than one generated image from a batch to have them all added as smart objects. Perhaps a checkbox or shift+clicking to multi select.

**Comment by isekaidev** [comment]
<img width="556" alt="image" src="https://user-images.githubusercontent.com/118139897/215876552-ea5d6dba-5bc5-4638-8efc-7a6b3ed20ddf.png">
